services:
  postgres:
    image: postgres:15
    container_name: postgres115
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - keycloak_network
    ports:
      - 5432:5432
      
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start", "--https-port", "8443"]
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      #KC_HOSTNAME_PORT: 8443
      KEYCLOAK_HTTP_PORT: 9090
      KEYCLOAK_HTTPS_PORT: 8443
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_PROXY_HEADERS: forwarded
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true      
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Nji98uhb@1008
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres      
      KC_METRICS_ENABLED: true
      #KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/keycloak.key
      #KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/keycloak.crt
      #KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/keycloak.key
      #KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/keycloak.crt
      KC_PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - 9090:8080
    volumes:
      - /etc/ssl/certs/keycloak.crt:/opt/keycloak/conf/keycloak.crt
      - /etc/ssl/private/keycloak.key:/opt/keycloak/conf/keycloak.key
      
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
